name: Deploy to GitHub Pages
on:
  push:
    branches: [test]  # 仅从 test 分支触发部署
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json  # 缓存 client 依赖

      # 关键修改 1：进入 client 目录，用 GitHub 专属配置构建
      - name: Install dependencies and build (GitHub Pages)
        shell: bash  # 新增：强制用 bash 执行，确保 cd 命令持久生效
        run: |
          cd client  # 必须进入 client 目录（前端代码在此）
          npm config set registry https://registry.npmmirror.com/  # 新增：切换为淘宝源，加速依赖下载
          npm install --verbose  # 新增 --verbose：输出详细安装日志，方便排查超时
          npm run build:github  # 执行关联 github 配置的构建命令（后续步骤会加这个脚本）

      # 关键修改 2：部署目录指向 client/dist（实际构建产物目录）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist  # 正确指向 Vite 构建产物
          force_orphan: true  # 清空旧 Pages 内容，避免干